# Basic CMS configuration
backend:
  name: git-gateway
  branch: main

# Media settings
media_folder: "public/images"
public_folder: "/images"

# Content collections
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/pages/home.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Button Text", name: "ctaText", widget: "string"}
              - {label: "Button Link", name: "ctaLink", widget: "string"}